### PR TITLE
Update to Elm v0.18

### PR DESCRIPTION
**Pull request by icidasset**
Hey 👋 

I wanted to use your `elm-sha` library, but it isn't updated to Elm v0.18 yet.
So I started upgrading that library and its dependencies.

I'm a bit stuck on the tests here though,
they seem to be failing, but I have no idea why.
Can you take a look? Please 🙏 ☺️ 

Changelog:
- Upgraded to the latest `elm-lang/core`, which changed some involved code (i.e. `shiftLeft -> shiftLeftBy`  and maybe more)
- Upgraded to the latest `elm-community/elm-test`, the api changed a lot here

Test results:

```
↓ Tests for UTF-8 encode/decode library
↓ UTF-8 Encoding/Decoding
✗ UTF-8 to Unicode

    "6 8 5 1"
    ╷
    │ Expect.equal
    ╵
    "æ ø å ñ"


↓ Tests for UTF-8 encode/decode library
↓ UTF-8 Encoding/Decoding
✗ Unicode to UTF-8

    "À¦ À¸ À¥ À±"
    ╷
    │ Expect.equal
    ╵
    "Ã¦ Ã¸ Ã¥ Ã±"
```

### CODE REVIEW

**Comment by gentauro** [comment]
Hi @icidasset.

I actually got stock here (we actually exactly the same `Main.elm` file):

https://github.com/icidasset/elm-utf8/blob/upgrade-to-latest-elm/tests/elm-package.json

My issue is after I have upgraded and added `elm-community/elm-test` my test cases no longer produce any output when I run:

```
mon@razerRamon:~/spiseMisu/code/elm-utf8/tests$ cat run-tests.sh 
#!/bin/sh

set -e

elm-make --yes --output test.js Main.elm
node test.js
```

Therefore I got stocked in the overall upgrade of my `UTF8` -> `SHA` -> `MerkleTree` libs. But as soon I'm done with current project I will upgrade them for sure (as I will need them for my next App). That said, if I can get my test working locally (my `run-tests.sh` file) I would gladly help upgrading the `UTF8` lib :+1:

**Comment by gentauro** [comment]
Oh, now I see the issue :+1: 

If you look into your code:

- https://github.com/icidasset/elm-utf8/blob/upgrade-to-latest-elm/src/UTF8.elm#L122-L144

I can see that you haven't gone full-in with the new `Bitwise` operators. Besides renaming some of the functions, Evan actually swapped the binding on the functions (precedence) in order to be able to write in a flow manner using `pipes` and therefore minimizing the amount of operators we have to define (they will all be deleted when I upgrade the lib) while increasing readability (just compare `baz` with `qux`). Here is an example that I just wrote so you can see it (it actually works):

```
import Array exposing (..) 
import Bitwise exposing (..) 
import Char exposing (..) 
import Html exposing (text)
import String exposing (..) 

stringify : KeyCode -> String
stringify =
    fromCode >> fromChar
    
strToCharArray : String -> Array Char
strToCharArray =
    String.toList >> Array.fromList

getKeyCode : Int -> Array Char -> KeyCode
getKeyCode i xs =
    case Array.get i xs of
        Just c ->
            c |> toCode

        Nothing ->
            0

(.&) : Int -> Int -> Int
(.&) =
    Bitwise.and


(.|) : Int -> Int -> Int
(.|) =
    Bitwise.or


(.<<) : Int -> Int -> Int
(.<<) =
    Bitwise.shiftLeftBy


(.>>) : Int -> Int -> Int
(.>>) =
    Bitwise.shiftRightBy

foo : Char -> String
foo c =
    let
        cc =
            c |> toCode
    in
        ((0xC0 .| (cc .>> 6)) |> stringify)
            ++ ((0x80 .| (cc .& 0x3F)) |> stringify)

bar : Char -> String
bar c =
    let
        cc =
            c |> toCode
            
        f =
          cc
            |> Bitwise.shiftRightBy 6
            |> Bitwise.or 0xC0
            |> stringify
        b = 
          cc
            |> Bitwise.and 0x3F
            |> Bitwise.or 0x80
            |> stringify
    in
      f ++ b
      
baz : String -> String
baz two =
    let
        xs =
            strToCharArray two
    in
        ((((getKeyCode 0 xs) .& 0x1F) .<< 6)
            .| ((getKeyCode 1 xs) .& 0x3F)
        )
            |> stringify

qux : String -> String
qux two =
    let
        xs =
            strToCharArray two
            
        f =
          getKeyCode 0 xs
            |> Bitwise.and 0x1F
            |> Bitwise.shiftLeftBy 6
            
        b =
          getKeyCode 1 xs
            |> Bitwise.and 0x3F
    in
      f
        |> Bitwise.or b
        |> stringify

main =
  text <| 
    "Foo: " ++ (foo 'æ') ++ 
    " and Bar: " ++ (bar 'æ') ++
    " and Baz: " ++ (baz "Ã¦") ++
    " and Qux: " ++ (qux "Ã¦")
```

*Output*:
```
Foo: À¦ and Bar: Ã¦ and Baz: 6 and Qux: æ
```

`foo` and `baz` are my old code and `bar` and `qux` are the new way of doing it :+1: If you re-write my code complying with the new way (you will also have to do it in the SHA library) I will gladly accept your pull request (as I said before, I really need to finish my current ongoing project).

> Note: 'foo' and 'baz' actually don't work anymore as the new precedence makes the old code work bizarre. I really would have hopped for a breaking change (`syntactic versioning`).

**Comment by gentauro** [comment]
Hi again @icidasset 

I already wrote the code and found out that I just needed to run `elm-test` from the root directory :+1: 

- http://package.elm-lang.org/packages/spisemisu/elm-utf8/1.0.1

Let see if I also can manage to upgadre `SHA` as easily as the `UTF8` lib.

I'm going to close this pull request as it no longer is relevant. But thanks for using the library :100:

**Comment by icidasset** [comment]
Thanks! 😄 🎉

**Comment by gentauro** [comment]
There you go. Happy coding :1st_place_medal: 

- http://package.elm-lang.org/packages/spisemisu/elm-sha/latest

**Comment by icidasset** [comment]
@gentauro Thank you so much! ☺️

**Comment by gentauro** [comment]
My pleasure :+1:

**Pull request closed without merging**
